name: Build Docker

on:
    push:
        branches:
            - main

jobs:
    publish_image:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1

            -   name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ github.repository_owner }}
                    password: ${{ secrets.ACCESS_TOKEN }}

            -   name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: .docker/Dockerfile
                    push: true
                    tags: symplify/monorepo-split-github-action:latest

            # docker-build . --quiet returns the ID of build container, so we can run it immediately
            - name: Test Docker image
              run: docker run $(docker build . --quiet)
