name: Build Docker

on:
    push:
        branches:
            - main

jobs:
    publish_image:
        name: Push Docker image to GitHub Packages
        runs-on: ubuntu-latest
        steps:
            -   name: Check out the repo
                uses: actions/checkout@v2
            -   name: Push to GitHub Packages
                uses: docker/build-push-action@v1
                with:
                    dockerfile: .docker/Dockerfile
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}
                    registry: docker.pkg.github.com
                    repository: symplify/monorepo-split-github-action/splitter
                    tag_with_ref: true

            # docker-build . --quiet returns the ID of build container, so we can run it immediately
            - name: Test Docker image
              run: docker run $(docker build . --quiet)
