name: 'Self Test With Tag'

on: [push]

jobs:
    self_test_with_tag:
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
                # this is required for "WyriHaximus/github-action-get-previous-tag" workflow
                with:
                    fetch-depth: 100

            # see https://github.com/WyriHaximus/github-action-get-previous-tag
            -
                id: previous_tag
                uses: "WyriHaximus/github-action-get-previous-tag@master"

            -
                # Uses an action in the root directory
                uses: ./
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'tests/packages/some-package'
                    split-repository-organization: 'TomasVotruba'
                    split-repository-name: 'github-action-monorepo-split-test'
                    tag: ${{ steps.previous_tag.outputs.tag }}
